import * as React from "react";
import PageLayout from "../components/PageLayout";
import Banner from "../components/Banner";
import "../index.css";
import {
  Template,
  GetPath,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
 
 
 export const config: TemplateConfig = {
   name: "index",
 };
 
 
  export const getPath: GetPath<TemplateProps> = ({document}) => {
    return `index.html`;
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  return {
    title: "Home Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

  const Index: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
  const {
    _site, 
  } = document;

   return (
    <>
      <PageLayout _site={_site}>
        <Banner text="Home Page"></Banner>
        <div className="centered-container">
          <div className="section space-y-10 px-10">
              <h1 className="text-center">Welcome to {_site.name}!</h1>
              <div className="px-14 space-y-5">
                <p>
                  {_site.name} was created by a group of technology experts based in New York City. They want to not only provide perfect answers everywhere... but perfect <i><strong>tacos</strong></i> everywhere! The authentic taste comes from family recipes and from fresh, simple and tasteful ingredients straight from home. In every taco from{_site.name} there is a bit of true Mexican culture and flavor.
                </p>
            </div>
          </div>
        </div>
      </PageLayout>
    </>
   );
 };
 
 export default Index;
 